#!/bin/bash

OS_TYPE="$(uname)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
EMSDK_DIR="$(cd "$SCRIPT_DIR/../../vendor/emsdk" &> /dev/null && pwd)"

echo "Generating build files for $OS_TYPE and Emscripten build files..."

if [[ "$OS_TYPE" == "Darwin" ]]; then
    if command -v xcodebuild &> /dev/null; then
        GENERATOR="Xcode"
        echo "Xcode detected - using Xcode generator"
    else
        GENERATOR="Ninja Multi-Config"
        echo "Xcode not found - using Ninja Multi-Config"
    fi
else
    GENERATOR="Ninja Multi-Config"
fi


(
    $EMSDK_DIR/emsdk install latest
    $EMSDK_DIR/emsdk activate latest

    chmod +x $EMSDK_DIR/emsdk_env.sh
    source $EMSDK_DIR/emsdk_env.sh

    emcmake cmake -B build-wasm -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE=$EMSDK_DIR/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
)

cmake -B build-native -G "$GENERATOR" -DCMAKE_BUILD_TYPE=Debug

if [ $? -ne 0 ]; then
    echo "Failed to generate project files!"
    exit 1
fi

echo ""
echo "Project generation completed successfully!"
echo "Native build files are located in the 'build-native' directory."
echo "WASM build files are located in the 'build-wasm' directory."
echo ""

if [[ "$GENERATOR" == "Xcode" ]]; then
    echo "To build the project:"
    echo "  cmake --build build-native --config Debug"
    echo "  cmake --build build-native --config Release"
    echo ""
    echo "WASM building:"
    echo "  cmake --build build-wasm --config Debug"
    echo "  cmake --build build-wasm --config Release"
    echo ""
    echo "To open in Xcode:"
    echo "  open build-native/Crimson.xcodeproj"
else
    echo "To build the project:"
    echo "  cmake --build build-native --config Debug"
    echo "  cmake --build build-native --config Release"
    echo ""
    echo "WASM building:"
    echo "  cmake --build build-wasm --config Debug"
    echo "  cmake --build build-wasm --config Release"
fi

echo ""
echo "To develop:"
echo "  Open folder in VS Code"
echo ""
