# OutBreak Docker Compose Configuration

services:
  outBreak:
    build:
      context: ../../../
      dockerfile: games/outBreak/docker/Dockerfile

    image: ghcr.io/domasles/crimson/outbreak:latest
    container_name: outBreak

    ports:
      - "0.0.0.0:80:80"

    restart: unless-stopped
